GroceryPackage/main/default/objects/Product2/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NewArrival</fullName>
            </value>
            <value>
                <fullName>BestSeller</fullName>
            </value>
            <value>
                <fullName>OnSale</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GroceryPackage/main/default/objects/Product2/fields/Image__c.field-meta.xml
<CustomField>
    <fullName>Image__c</fullName>
    <label>Image</label>
    <type>Url</type>
</CustomField>

GroceryPackage/main/default/objects/Product2/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

GroceryPackage/main/default/classes/ProductController.cls
public with sharing class ProductController {


    //Handler to set stock quantity same as product quantity when creat products
    public static void CheckStock(List<Product2> products) {
        for(Integer i = 0; i < products.size(); i++) {
            if(products[i].Quantity__c != products[i].StockQuantity__c) {
                products[i].StockQuantity__c = products[i].Quantity__c;
            }
        }
    }

    //Get current products
    @AuraEnabled
    public static List<Product2> GetProducts() {

        List<Product2> allProducts = [SELECT Name, ProductCode, Category__c, Image__c,Price__c, Description, Quantity__c,StockQuantity__c FROM Product2];

        return allProducts;
    }

    @AuraEnabled
    public static void SaveProducts(List<Product2> newProducts){
        Insert newproducts;
    }
}