GroceryPackage/main/default/objects/Cart__c/Cart__c.object-meta.xml
<CustomObject>
    <label>Cart</label>
    <nameField>
        <label>Cart Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Carts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GroceryPackage/main/default/objects/Item__c/Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GroceryPackage/main/default/objects/Item__c/fields/Cart__c.field-meta.xml
<CustomField>
    <fullName>Cart__c</fullName>
    <label>Cart</label>
    <referenceTo>Cart__c</referenceTo>
    <relationshipLabel>Items</relationshipLabel>
    <relationshipName>Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

GroceryPackage/main/default/objects/Item__c/fields/ItemPrice__c.field-meta.xml
<CustomField>
    <fullName>ItemPrice__c</fullName>
    <label>ItemPrice</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

GroceryPackage/main/default/objects/Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Items</relationshipLabel>
    <relationshipName>Items1</relationshipName>
    <type>Lookup</type>
</CustomField>

GroceryPackage/main/default/classes/ItemController.cls
public with sharing class ItemController {
    public ItemController() {

    }

    //In Items after insert trigger, decrease item quantity from Product stock quantity, and save the new stock quantity
    public static void HandleProductQuantity(List<Item__c> newItems) {
        List<Id> productIds = new List<Id>();
        for(Integer i = 0; i < newItems.size();i++) {
            productIds.add(newItems[i].Product__c);
        }
        List<Product2> productList = [SELECT Name,Quantity__c,StockQuantity__c FROM Product2 WHERE Id IN :productIds];
        for(Integer i = 0; i < productList.size(); i++) {
            Integer index = FindIndexOfItems(newItems, productList[i].Id);
            if(index != -1) {
                productList[i].StockQuantity__c -= newItems[index].Quantity__c; 
            }
        }
        Update productList;
    }

    //Search index of product id from the list of items
    @testVisible private static Integer FindIndexOfItems(List<Item__c> items, Id id) {
        for(Integer i = 0; i < items.size();i++) {
            if(items[i].Product__c == id) {
                return i;
            }
        }
        return -1;
    }

    @AuraEnabled
    public static void SaveItems(List<Item__c> newItems){
        try {
            List<Item__c> cartItems = new List<Item__c>();
            for(Integer i = 0; i < newItems.size(); i++) {
                Item__c newItem = new Item__c(
                    id__c = newItems[i].id__c,
                    Name = newItems[i].Name,
                    ItemPrice__c = newItems[i].ItemPrice__c,
                    Quantity__c = newItems[i].Quantity__c,
                    Product__c = newItems[i].Product__c, 
                    Cart__c = newItems[i].Cart__c
                );
                cartItems.add(newItem);
            }  
            Insert cartItems;          
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}