GroceryPackage/main/default/objects/Cart__c/Cart__c.object-meta.xml
<CustomObject>
    <label>Cart</label>
    <nameField>
        <label>Cart Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Carts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GroceryPackage/main/default/objects/Cart__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Carts</relationshipLabel>
    <relationshipName>Carts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

GroceryPackage/main/default/objects/Cart__c/fields/Total_price__c.field-meta.xml
<CustomField>
    <fullName>Total_price__c</fullName>
    <label>Total price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

GroceryPackage/main/default/classes/AccountController.cls
public with sharing class AccountController {
    public AccountController() {

    }
    @AuraEnabled
    public static List<Account> GetAccountList(){
        try {
            List<Account> allAccounts = [SELECT Name,(SELECT Name,Account__c,Quantity__c,Total_price__c FROM Carts__r) FROM Account WHERE Active__c = 'Yes'];
            return allAccounts;            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}