GroceryPackage/main/default/objects/Cart__c/Cart__c.object-meta.xml
<CustomObject>
    <label>Cart</label>
    <nameField>
        <label>Cart Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Carts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GroceryPackage/main/default/objects/Cart__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Carts</relationshipLabel>
    <relationshipName>Carts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

GroceryPackage/main/default/objects/Cart__c/fields/Total_price__c.field-meta.xml
<CustomField>
    <fullName>Total_price__c</fullName>
    <label>Total price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

GroceryPackage/main/default/objects/Item__c/Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GroceryPackage/main/default/objects/Item__c/fields/Cart__c.field-meta.xml
<CustomField>
    <fullName>Cart__c</fullName>
    <label>Cart</label>
    <referenceTo>Cart__c</referenceTo>
    <relationshipLabel>Items</relationshipLabel>
    <relationshipName>Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

GroceryPackage/main/default/objects/Item__c/fields/ItemPrice__c.field-meta.xml
<CustomField>
    <fullName>ItemPrice__c</fullName>
    <label>ItemPrice</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

GroceryPackage/main/default/objects/Item__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

GroceryPackage/main/default/objects/Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Items</relationshipLabel>
    <relationshipName>Items1</relationshipName>
    <type>Lookup</type>
</CustomField>

GroceryPackage/main/default/objects/Product2/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NewArrival</fullName>
            </value>
            <value>
                <fullName>BestSeller</fullName>
            </value>
            <value>
                <fullName>OnSale</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GroceryPackage/main/default/objects/Product2/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

GroceryPackage/main/default/classes/ItemControllerTest.cls
@isTest
private class ItemControllerTest {
    @TestSetup
    static void makeData(){

        // Create 3 accounts for test usage
        List<Account> accountsToInsert = new List<Account>();
        for(Integer num = 0; num < 3; num++) {
            accountsToInsert.add(new Account(name = 'Test Account ' + num));
        }
        
        Insert accountsToInsert;

        List<Account> accountList = [SELECT Name, Id FROM Account];

        List<Cart__c> newCarts = new List<Cart__c>();
        
        //Creat 2 carts for test usage
        for(Integer i = 0; i < 2; i++) {
            Cart__c newCart = new Cart__c(
            Account__c = accountList[0].Id,
            Order_Number__c = 1 + i,
            Quantity__c = 20 *(i+1),
            Total_price__c = 40 * (i+1));
            newCarts.add(newCart);
        }
        Insert newCarts;

        //Insert two products for test
        List<Product2> newProducts = new List<Product2>();
        List<String> productNames = new String[3];
        productNames[0] = 'Apple';
        productNames[1] = 'Pear';

        for(Integer i = 0; i < 2; i++) {
            Product2 newProduct = new Product2(
                Name = productNames[i],
                ProductCode = '001' + i, 
                Category__c = 'OnSale', 
                Price__c = 2.99, 
                Quantity__c = 1000,
                StockQuantity__c = 1000
            );
            newProducts.add(newProduct);
        }     
        Insert newProducts;
        
    }

    @isTest 
    static void NP_SaveItems() {
        Test.startTest();
        List<Product2> allProducts = [SELECT Name, Id, Price__c FROM Product2];
        List<Cart__c> allCarts = [SELECT Id FROM Cart__c];
        
        List<Item__c> cartItems = new List<Item__c>();
        for(Integer i = 0; i < 2; i++) {
            
            Item__c newItem = new Item__c(
                id__c = i+1,
                Name = allProducts[i].Name,
                ItemPrice__c = allProducts[i].Price__c,
                Quantity__c = 100,
                Product__c = allProducts[i].Id, 
                Cart__c = allCarts[0].Id
            );
            cartItems.add(newItem);
        }  
        ItemController.SaveItems(cartItems); 
        List<Item__c> result = [SELECT Id,Quantity__c FROM Item__c];    
        System.assertEquals(2,result.size());

        allProducts = [SELECT Name, Id, Price__c,StockQuantity__c FROM Product2];
        System.assertEquals(900, Integer.valueOf(allProducts[0].StockQuantity__c));
        Test.stopTest();
    }
}